-- *****************************************************************************
-- This script contains INSERT statements for populating tables with seed data
-- *****************************************************************************

BEGIN;
insert into users (login_name, email_id, password, role_id, salt_code) VALUES ('vel', 'blah@blah.com', 'vel',2, '123456');
insert into users (login_name, email_id, password, role_id, salt_code) VALUES ('patrick', 'blah@blah.com', 'patrick',1, '123456');
insert into users (login_name, email_id, password, role_id, salt_code) VALUES ('jeremy', 'blah@blah.com', 'jeremy',3, '123456');
insert into users (login_name, email_id, password, role_id, cohort) values ('adam1', 'adam@hotmail.com', 'Bernie1090!', 1, 4);
insert into users (login_name, email_id, password, role_id, cohort) values ('pstefan420', 'pstefan@netscape.com', 'Bernie1090!', 1, 4);
insert into users (login_name, email_id, password, role_id, cohort) values ('craig23', 'craig@craig.com', 'Bernie1090!', 1, 4);
insert into users (login_name, email_id, password, role_id, cohort) values ('lexi', 'alexis@chipotle.com', 'Bernie1090!', 1, 3);
insert into users (login_name, email_id, password, role_id, cohort) values ('beermatt', 'matt@beer.com', 'Bernie1090!', 1, 3);
insert into users (login_name, email_id, password, role_id, cohort) values ('jammie', 'jammie@jammie.com', 'Bernie1090!', 1, 3);
insert into users (login_name, email_id, password, role_id, cohort) values ('allen', 'allen@yu.com', 'Bernie1090!', 1, 2);
insert into users (login_name, email_id, password, role_id, cohort) values ('bubba1', 'david@techelevator.com', 'Bernie1090!', 1, 2);
insert into users (login_name, email_id, password, role_id, cohort) values ('guy', 'matt@beer.com', 'Bernie1090!', 1, 2);
insert into users (login_name, email_id, password, role_id, cohort) values ('pattt', 'jammie@jammie.com', 'Bernie1090!', 1, 1);
insert into users (login_name, email_id, password, role_id, cohort) values ('kelly', 'allen@yu.com', 'Bernie1090!', 1, 1);
insert into users (login_name, email_id, password, role_id, cohort) values ('josh', 'david@techelevator.com', 'Bernie1090!', 1, 1);
insert into users (login_name, email_id, password, role_id ) values ('joe', 'jammie@jammie.com', 'Bernie1090!', 2);
insert into users (login_name, email_id, password, role_id) values ('Antony', 'allen@yu.com', 'Bernie1090!', 2);
insert into users (login_name, email_id, password, role_id) values ('Andria', 'david@techelevator.com', 'Bernie1090!', 2);
insert into users (login_name, email_id, password, role_id ) values ('PNC', 'jammie@jammie.com', 'Bernie1090!', 3);
insert into users (login_name, email_id, password, role_id) values ('Hyland', 'allen@yu.com', 'Bernie1090!', 3);
insert into users (login_name, email_id, password, role_id) values ('Medical mutual', 'david@techelevator.com', 'Bernie1090!', 3);
insert into users (login_name, email_id, password, role_id, cohort) values ('adam1', 'adam@hotmail.com', 'Bernie1090!', 1, 4);
insert into users (login_name, email_id, password, role_id, cohort) values ('pstefan420', 'pstefan@netscape.com', 'Bernie1090!', 1, 4);
insert into users (login_name, email_id, password, role_id, cohort) values ('craig23', 'craig@craig.com', 'Bernie1090!', 1, 4);
insert into users (login_name, email_id, password, role_id, cohort) values ('lexi', 'alexis@chipotle.com', 'Bernie1090!', 1, 4);
insert into users (login_name, email_id, password, role_id, cohort) values ('beermatt', 'matt@beer.com', 'Bernie1090!', 1, 4);
insert into users (login_name, email_id, password, role_id, cohort) values ('jammie', 'jammie@jammie.com', 'Bernie1090!', 1, 4);
insert into users (login_name, email_id, password, role_id, cohort) values ('adam1', 'adam@hotmail.com', 'Bernie1090!', 1, 3);
insert into users (login_name, email_id, password, role_id, cohort) values ('pstefan420', 'pstefan@netscape.com', 'Bernie1090!', 1, 3);
insert into users (login_name, email_id, password, role_id, cohort) values ('craig23', 'craig@craig.com', 'Bernie1090!', 1, 3);
insert into users (login_name, email_id, password, role_id, cohort) values ('lexi', 'alexis@chipotle.com', 'Bernie1090!', 1, 3);
insert into users (login_name, email_id, password, role_id, cohort) values ('beermatt', 'matt@beer.com', 'Bernie1090!', 1, 3);
insert into users (login_name, email_id, password, role_id, cohort) values ('jammie', 'jammie@jammie.com', 'Bernie1090!', 1, 3);
insert into users (login_name, email_id, password, role_id, cohort) values ('adam1', 'adam@hotmail.com', 'Bernie1090!', 1, 2);
insert into users (login_name, email_id, password, role_id, cohort) values ('pstefan420', 'pstefan@netscape.com', 'Bernie1090!', 1, 2);
insert into users (login_name, email_id, password, role_id, cohort) values ('craig23', 'craig@craig.com', 'Bernie1090!', 1, 2);
insert into users (login_name, email_id, password, role_id, cohort) values ('lexi', 'alexis@chipotle.com', 'Bernie1090!', 1, 2);
insert into users (login_name, email_id, password, role_id, cohort) values ('beermatt', 'matt@beer.com', 'Bernie1090!', 1, 2);
insert into users (login_name, email_id, password, role_id, cohort) values ('jammie', 'jammie@jammie.com', 'Bernie1090!', 1, 2);
insert into users (login_name, email_id, password, role_id, cohort) values ('adam1', 'adam@hotmail.com', 'Bernie1090!', 1, 1);
insert into users (login_name, email_id, password, role_id, cohort) values ('pstefan420', 'pstefan@netscape.com', 'Bernie1090!', 1, 1);
insert into users (login_name, email_id, password, role_id, cohort) values ('craig23', 'craig@craig.com', 'Bernie1090!', 1, 1);
insert into users (login_name, email_id, password, role_id, cohort) values ('lexi', 'alexis@chipotle.com', 'Bernie1090!', 1, 1);
insert into users (login_name, email_id, password, role_id, cohort) values ('beermatt', 'matt@beer.com', 'Bernie1090!', 1, 1);
insert into users (login_name, email_id, password, role_id, cohort) values ('jammie', 'jammie@jammie.com', 'Bernie1090!', 1, 1);


insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Adam', 'Gonzalez', 'Master ping pong player. World renowned scientist. Inventor of Google2.', 'adam@hotmail.com', 4, 'BS', 'Cool dude', '(774)299-7466', 'Java, Oil', true, true);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Patrick', 'Stefan', 'Rock star.', 'pstefan@netscape.com', 5, 'MS', 'Communicator', '(216)555-5555', 'Java', true, true);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Craig', 'Castelaz', 'Cooler than Woz', 'craig@craig.com', 6, 'BS', 'Cooler than the other side of the pillow', '(216)000-0000', 'Java', true, true);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Alexis', 'Thomas', 'Give me Chipotle or give me death!', 'alexis@chipotle.com', 7, 'BS', 'Crazy', '(774)299-7466', 'Chipotle', true, true);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Matt', 'Dowling', 'Food. Beer. Insults.', 'matt@beer.com', 8, 'Ph.D', 'Null', '(774)299-7466', 'See summary', true, true);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Michael', 'Clark', ' AKA Jammie. Better known as the Master of Dance and Trickery', 'jammie@jammie.com', 9, 'Ph.D', 'Dance, Trickery', '(774)299-7466', 'Jammie', true, true);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Allen', 'Yu', 'Proud St. Ignatius alum. Cider lover.', 'allen@yu.com', 10, 'AS', 'Best laugh ever', '(774)299-7466', 'Cider', true, true);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('David', 'Wintrich', 'Lost a bet, have to go back to school to learn C-Sharp.', 'david@techelevator.com', 11, 'HS', 'Java', '(774)299-7466', 'Java', true, false);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Kasi', 'Balak', 'Super programmer.', 'kasi@techelevator.com', 12, 'Ph.D', 'Managerial', '(216)499-7466', 'Programming, Hiking, Cooking', true, false);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Kevin', 'Crumbley', ' Stellar student looking to expand knowledge of programming', 'kevin@jammie.com', 13, 'BS', 'Coding', '(774)299-7766', 'Java', true, false);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Shawn', 'Roberts', 'Former rodeo star turned programmer', 'shawn@yu.com', 14, 'AS', 'Great communicator', '(774)299-7466', 'Cider', true, false);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Addison', 'ulahaq', 'DJ and programmer', 'addison@techelevator.com', 15, 'HS', 'Java', '(774)299-7466', 'Java', true, false);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Jammie', 'Jones', 'I dont know', 'jammie@hotmail.com', 16, 'AS', 'Punctuality', '(888)299-7466', 'Java', true, true);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Lawrence', 'Stefanski', 'Former professor at Harvard', 'lawr@harvard.com', 17, 'MS', 'Leadership', '(216)444-5555', 'C-Sharp', true, true);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Clark', 'Gable', 'New coder who loves databases', 'clark@crag.com', 18, 'HS', 'Managerial experience', '(216)000-0000', 'Movies', true, false);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Alexis', 'Trebek', 'I would like to work at a financial institution', 'alex@chipotle.com', 19, 'BS', 'Public speaking', '(216)299-7466', 'Javascript', true, false);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Matt', 'Foghorn', 'Long time IT guy looking to expand my knowledge', 'matt@itguy.com', 20, 'Ph.D', 'Relationship building', '(774)999-7466', 'See summary', true, true);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Sarah', 'Guttenberg', 'Passionate coder looking to contribute to a company', 'sarah@jammie.com', 21, 'BS', 'Dance, Trickery', '(444)299-7466', 'Jammie', true, false);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Allen', 'Yu Jr.', 'Following in my fathers footsteps going to Tech Elevator', 'allenjr@yu.com', 22, 'AS', 'Best laugh ever, also', '(774)299-7466', 'Cider is great', true, true);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Brandon', 'Weedan', 'Former NFL quarterback', 'brandon@techelevator.com', 23, 'AS', 'Java', '(774)299-7466', 'Java', true, false);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Bill', 'Gates', 'Retiree just having fun', 'bill@java.com', 24, 'HS', 'None', '(216)924-4450', 'Java', true, false);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Lauren', 'Sanders', ' All about coding', 'lauren@jammie.com', 25, 'Ph.D', 'Friendly', '(774)299-7466', 'C-Sharp', true, true);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Francis', 'Thomas', 'Hoping to make it in Silicon Valley', 'francis@francis.com', 26, 'HS', 'Leader', '(774)299-7466', 'C-Sharp', true, false);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Brad', 'Bradley', 'Venture capatalist', 'brad@techelevator.com', 27, 'Ph.D', 'Adaptable', '(774)299-7466', 'Java', true, true);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Ollie', 'Warner', 'I like to live in the country', 'ollie@hotmail.com', 28, 'BS', 'Cunning', '(774)299-7466', 'Java', true, true);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Peter', 'Staltz', 'Running a large law firm', 'peter@largelawfirm.com', 29, 'MS', 'Communicator', '(216)555-5555', 'Java', true, false);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Tiffany', 'Carter', 'Trying to expand my skill set', 'tiff@gmail.com', 30, 'AS', 'I love cooking and coding', '(216)000-0000', 'C-Sharp', true, false);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Annie', 'Targus', 'Transitioning from HR to IT', 'annie@netscape.com', 31, 'BS', 'Leadership', '(774)299-7466', 'Chipotle', true, true);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Mary', 'Douglas', 'Coding is so cool', 'mary@coding.com', 32, 'Ph.D', 'Conflict mediator', '(774)299-7466', 'Curling', true, false);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Michaela', 'Jacqson', 'Front end development is my biggest passion', 'j@gmail.com', 33, 'HS', 'Intellect', '(774)299-7466', 'Jammie', true, true);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Al', 'Hamburg', 'Javascript is so cool', 'al@gamil.com', 34, 'AS', 'Believer', '(774)299-7466', 'Coding', true, true);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Daniella', 'Lachina', 'Super smart social worker', 'dani@techelevator.com', 35, 'MS', 'Everything', '(774)299-7466', 'Java', true, false);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Karl', 'Hungus', 'Musician trying to make it in a brave new world', 'karl@nihlist.com', 36, 'HS', 'Adaptable', '(774)299-7466', 'Marmots', true, true);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Tairy', 'Greene', 'Actor turned programmer', 'tairy@greene.com', 37, 'Ph.D', 'Negotiator', '(774)299-7466', 'Java', true, true);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Bobby', 'Stoan', 'Old Cobol developer learning C-Sharp', 'bobby23@netscape.com', 38, 'HS', 'Leadership', '(774)299-7466', 'C-Sharp', true, false);
insert into students (first_name, last_name, summary, email_id, user_id, academic_background, soft_skills, phone_number, interests, public, industry_experience) values ('Spraynard', 'Kruger', 'I love regular expressions', 'spraynard@techelevator.com', 39, 'MS', 'Jovial', '(774)299-7466', 'Ukelele', true, false);

insert into admins (user_id, first_name, last_name) values (16, 'Norma', 'Garcia');
insert into admins (user_id, first_name, last_name) values (17, 'Davi', 'Wintrich');
insert into admins (user_id, first_name, last_name) values (18, 'Anthony', 'Huges');


insert into employers (user_id, name) values (19, 'pnc');
insert into employers (user_id, name) values (20, 'Hyland');
insert into employers (user_id, name) values (12, 'Medical Mutual');


insert into portfolios (student_id) values (1);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (1, 'Google2', 'The best dang search engine ever created!', 'Java, Js, Html, Sql', 'https://www.google.com/', false);
insert into portfolios (student_id) values (2);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (2, 'Planet Paddy', 'Just rockin out', 'Java, Js', 'https://en.wikipedia.org/wiki/Music', false);
insert into portfolios (student_id) values (3);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (3, 'Fly By Night Bank', 'The only bank open at night. We are nocturnal apparently.', 'Html, Sql', 'www.goldmansachs.com/', true);
insert into portfolios (student_id) values (4);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (4, 'Chipotle 24/7', 'Opened the first digital Chipotle restaurant. Open 24/7. Just print your order on a 3-D printer!', 'Java, Css, Csharp', 'https://chipotle.com/', false);
insert into portfolios (student_id) values (5);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (5, 'Beer', 'Beer', 'Css', 'https://www.beer.com/', false);
insert into portfolios (student_id) values (6);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (6, 'Google3', 'My search engine is way better than Adams, his sucks', 'Js, Html', 'https://www.google.com/', false);
insert into portfolios (student_id) values (7);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (7, 'Google4', 'I had to one-up Michael. Sorry dude.', 'Java, Js, Html', 'https://www.google.com/', false);
insert into portfolios (student_id) values (8);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (8, 'Chipotle 24/7', 'Opened the first digital Chipotle restaurant. Open 24/7. Just print your order on a 3-D printer!', 'Java, Css, Csharp', 'https://chipotle.com/', false);
insert into portfolios (student_id) values (9);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (9, 'Beer', 'Beer', 'Css', 'https://www.beer.com/', false);
insert into portfolios (student_id) values (10);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (10, 'Google3', 'My search engine is way better than Adams, his sucks', 'Js, Html', 'https://www.google.com/', false);
insert into portfolios (student_id) values (11);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (11, 'Google4', 'I had to one-up Michael. Sorry dude.', 'Java, Js, Html', 'https://www.google.com/', false);
insert into portfolios (student_id) values (12);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (12, 'Google4', 'I had to one-up Michael. Sorry dude.', 'Java, Js, Html', 'https://www.google.com/', false);
insert into portfolios (student_id) values (13);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (13, 'Google2', 'The best dang search engine ever created!', 'Java, Js, Html, Sql', 'https://www.google.com/', false);
insert into portfolios (student_id) values (14);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (14, 'Planet Paddy', 'Just rockin out', 'Java, Js', 'https://en.wikipedia.org/wiki/Music', false);
insert into portfolios (student_id) values (15);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (15, 'Fly By Night Bank', 'The only bank open at night. We are nocturnal apparently.', 'Html, Sql', 'www.goldmansachs.com/', true);
insert into portfolios (student_id) values (16);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (16, 'Chipotle 24/7', 'Opened the first digital Chipotle restaurant. Open 24/7. Just print your order on a 3-D printer!', 'Java, Css, Csharp', 'https://chipotle.com/', false);
insert into portfolios (student_id) values (17);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (17, 'Beer', 'Beer', 'Css', 'https://www.beer.com/', false);
insert into portfolios (student_id) values (18);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (18, 'Google3', 'My search engine is way better than Adams, his sucks', 'Js, Html', 'https://www.google.com/', false);
insert into portfolios (student_id) values (19);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (19, 'Google4', 'I had to one-up Michael. Sorry dude.', 'Java, Js, Html', 'https://www.google.com/', false);
insert into portfolios (student_id) values (20);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (20, 'Chipotle 24/7', 'Opened the first digital Chipotle restaurant. Open 24/7. Just print your order on a 3-D printer!', 'Java, Css, Csharp', 'https://chipotle.com/', false);
insert into portfolios (student_id) values (21);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (21, 'Beer', 'Beer', 'Css', 'https://www.beer.com/', false);
insert into portfolios (student_id) values (22);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (22, 'Google3', 'My search engine is way better than Adams, his sucks', 'Js, Html', 'https://www.google.com/', false);
insert into portfolios (student_id) values (23);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (23, 'Google4', 'I had to one-up Michael. Sorry dude.', 'Java, Js, Html', 'https://www.google.com/', false);
insert into portfolios (student_id) values (24);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (24, 'Google4', 'I had to one-up Michael. Sorry dude.', 'Java, Js, Html', 'https://www.google.com/', false);
insert into portfolios (student_id) values (25);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (25, 'Google2', 'The best dang search engine ever created!', 'Java, Js, Html, Sql', 'https://www.google.com/', false);
insert into portfolios (student_id) values (26);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (26, 'Planet Paddy', 'Just rockin out', 'Java, Js', 'https://en.wikipedia.org/wiki/Music', false);
insert into portfolios (student_id) values (27);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (27, 'Fly By Night Bank', 'The only bank open at night. We are nocturnal apparently.', 'Html, Sql', 'www.goldmansachs.com/', true);
insert into portfolios (student_id) values (28);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (28, 'Chipotle 24/7', 'Opened the first digital Chipotle restaurant. Open 24/7. Just print your order on a 3-D printer!', 'Java, Css, Csharp', 'https://chipotle.com/', false);
insert into portfolios (student_id) values (29);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (29, 'Beer', 'Beer', 'Css', 'https://www.beer.com/', false);
insert into portfolios (student_id) values (30);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (30, 'Google3', 'My search engine is way better than Adams, his sucks', 'Js, Html', 'https://www.google.com/', false);
insert into portfolios (student_id) values (31);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (31, 'Google4', 'I had to one-up Michael. Sorry dude.', 'Java, Js, Html', 'https://www.google.com/', false);
insert into portfolios (student_id) values (32);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (32, 'Chipotle 24/7', 'Opened the first digital Chipotle restaurant. Open 24/7. Just print your order on a 3-D printer!', 'Java, Css, Csharp', 'https://chipotle.com/', false);
insert into portfolios (student_id) values (33);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (33, 'Beer', 'Beer', 'Css', 'https://www.beer.com/', false);
insert into portfolios (student_id) values (34);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (34, 'Google3', 'My search engine is way better than Adams, his sucks', 'Js, Html', 'https://www.google.com/', false);
insert into portfolios (student_id) values (35);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (35, 'Google4', 'I had to one-up Michael. Sorry dude.', 'Java, Js, Html', 'https://www.google.com/', false);
insert into portfolios (student_id) values (36);
insert into portfolios (student_id, project_name, project_description, technology_used, source_code_link, is_group_project) values (36, 'Google4', 'I had to one-up Michael. Sorry dude.', 'Java, Js, Html', 'https://www.google.com/', false);



COMMIT;